/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js the first time it runs in
// development. It is committed here as a stable seed so that ``pnpm
// typecheck`` works pre-install. Next.js will keep it up to date.
